apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  googleCloudBuild:
    projectId: hidden-digit-339515
  artifacts:
    - image: us.gcr.io/hidden-digit-339515/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.go"
            dest: .
    - image: us.gcr.io/hidden-digit-339515/book
      context: book
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.go"
            dest: .