apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-postgres
  template:
    metadata:
      name: book-postgres
      labels:
        app: book-postgres
    spec:
      containers:
        - name: book-postgres
          image: postgres
          env:
            - name: POSTGRES_HOST
              value: "book-postgres-srv"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password123"
            - name: POSTGRES_DB
              value: "golang_fiber"
