apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      name: auth-postgres
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres
          env:
            - name: POSTGRES_HOST
              value: "auth-postgres-srv"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password123"
            - name: POSTGRES_DB
              value: "golang_fiber"
